name: ci

on: pull_request
jobs:
    test:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          python-version: ["3.9", "3.10", "3.11", "3.12"]

      steps:
      - name: baixar reposit√≥rio
        run: actions/checkout@v4

      - name: instalar o python
        uses: actions/steup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      
      - name: instalar as libs
        run: pip install -r requirements.txt
      
      - name: rodar rotina de testes
        run: pytest tests/test_contrato.py
        
    





